### ISSUE TITLE
Have write functions work with tibble

### ISSUE THREAD

**Issue by SamPassmore** [SamPassmore/bayestraitr#5]
As pointed out in #4 the write functions only work with dataframes & not tibbles.

Currently the function throws an error if there is a tibble used in the data argument, but it would be better to just deal with tibbles as input possibilities.

**Comment by SimonGreenhill** [comment]
You could just explicitly cast to dataframe:
e.g. instead of:

https://github.com/SamPassmore/bayestraitr/blob/04bebe766f4c14d6ebb92defb8fee2a21144a2a6/R/write_files.R#LL21C3-L23C4

```{r}
if(class(data) == c("tbl_df", "tbl", "data.frame")){
    stop("Data cannot be a tibble. Please use a data.frame")
  }
```

you could do:

```{r}
if(class(data) == c("tbl_df", "tbl", "data.frame")){
    data <- as.dataframe(data)
  }
```
